INSERT INTO PAYMENT (DUE_DATE, AMOUNT, EMAIL)
VALUES (DATEADD(DAY, -1, CURRENT_DATE), 100.00, 'user1@example.com');

INSERT INTO PAYMENT (DUE_DATE, AMOUNT, EMAIL)
VALUES (DATEADD(DAY, -10, CURRENT_DATE), 200.00, 'user2@example.com');

INSERT INTO PAYMENT (DUE_DATE, AMOUNT, EMAIL)
VALUES (DATEADD(DAY, -60, CURRENT_DATE), 100.00, 'user3@example.com');

INSERT INTO PAYMENT (DUE_DATE, AMOUNT, EMAIL)
VALUES (DATEADD(DAY, 0, CURRENT_DATE), 400.00, 'user4@example.com');

INSERT INTO PAYMENT (DUE_DATE, AMOUNT, EMAIL)
VALUES (NULL, 500.00, 'user5@example.com');
